"""Numbers copied from MaoLiAo/define.h and the related capacity constants."""

from __future__ import annotations

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parents[2] / "data"


def _load() -> dict:
    with (DATA_DIR / "constants.json").open(encoding="utf-8") as fh:
        return json.load(fh)


CONSTANTS = _load()

XSIZE = CONSTANTS["XSIZE"]
YSIZE = CONSTANTS["YSIZE"]
WIDTH = CONSTANTS["WIDTH"]
HEIGHT = CONSTANTS["HEIGHT"]
X0 = CONSTANTS["X0"]
Y0 = CONSTANTS["Y0"]
TIME = CONSTANTS["TIME"]
STEP = CONSTANTS["STEP"]
ENEMY_STEP = CONSTANTS["ENEMY_STEP"]
K_MAP_BG = CONSTANTS["K_MAP_BG"]
XLEFT = CONSTANTS["XLEFT"]
XRIGHT = CONSTANTS["XRIGHT"]
REAL_HEIGHT = CONSTANTS["REAL_HEIGHT"]
UNREAL_HEIGHT = CONSTANTS["UNREAL_HEIGHT"]
G = CONSTANTS["G"]
V_MAX = CONSTANTS["V_MAX"]
A_ROLE = CONSTANTS["A_ROLE"]
T1 = CONSTANTS["T1"]
T2 = CONSTANTS["T2"]
T3 = CONSTANTS["T3"]
LIFE = CONSTANTS["LIFE"]
MAP_NUMBER = CONSTANTS["MAP_NUMBER"]
COINS_NUMBER = CONSTANTS["COINS_NUMBER"]
FOOD_NUMBER = CONSTANTS["FOOD_NUMBER"]
ENEMY_TOTE = CONSTANTS["ENEMY_TOTE"]
BOMB_NUMBER = CONSTANTS["BOMB_NUMBER"]
BULLET_NUMBER = CONSTANTS["BULLET_NUMBER"]
LEHGTH_INTERVAL_BULLET = CONSTANTS["LEHGTH_INTERVAL_BULLET"]
TIME_INTERVAL_BULLET = CONSTANTS["TIME_INTERVAL_BULLET"]
MAX_DISTANCE = CONSTANTS["MAX_DISTANCE"]

CMD_LEFT = CONSTANTS["CMD_LEFT"]
CMD_RIGHT = CONSTANTS["CMD_RIGHT"]
CMD_UP = CONSTANTS["CMD_UP"]
CMD_DOWN = CONSTANTS["CMD_DOWN"]
CMD_SHOOT = CONSTANTS["CMD_SHOOT"]
CMD_ESC = CONSTANTS["CMD_ESC"]
VIR_RETURN = CONSTANTS["VIR_RETURN"]
VIR_RESTART = CONSTANTS["VIR_RESTART"]
VIR_HOME = CONSTANTS["VIR_HOME"]

PIXELS_PER_METRE = UNREAL_HEIGHT / REAL_HEIGHT


def friction_u(bucket: str) -> float:
    """u = (V_MAX / T) / G for T in {T1, T2, T3}."""
    t = {"T1": T1, "T2": T2, "T3": T3}[bucket]
    return (V_MAX / t) / G
