// Paste-ready fragments for example-world-4-canyon.json.
// Regenerated by:
//   python3 examples/toolkit/maoliao_levels.py export-cpp \
//       examples/levels/example-world-4-canyon.json
//
// This file is documentation. It is not part of the Visual Studio project.
// The EasyX headers are not required to read it.

#if 0  // ----- Scene::createMap  (world == 4) -----
Map m[] = {
    { 0, 9, 1, 16, 1 },  // west-rim
    { 0, 10, 3, 16, 2 },  // west-fill
    { 22, 9, 1, 10, 1 },  // mid-mesa
    { 22, 10, 3, 10, 2 },  // mid-fill
    { 40, 9, 5, 8, 1 },  // east-approach
    { 40, 10, 4, 8, 2 },  // east-fill
    { 48, 9, 6, 3, 1 },  // slick-lip
    { 48, 10, 3, 3, 2 },  // slick-fill
    { 56, 9, 1, 40, 1 },  // finish-runway
    { 56, 10, 3, 40, 2 },  // finish-fill
    { 16, 7, 2, 2, 1 },  // gap-cloud-1
    { 19, 5, 2, 2, 1 },  // gap-cloud-2
    { 33, 6, 2, 3, 1 },  // mesa-cloud
    { 52, 6, 2, 2, 1 },  // slick-recovery
    { 28, 7, 10, 1, 1 },  // pipe-gate
    { 62, 7, 10, 1, 1 },  // pipe-gate
    { 8, 7, 11, 1, 1 },  // bg-grass
    { 44, 7, 11, 1, 1 },  // bg-grass
    { 70, 7, 11, 1, 1 },  // bg-grass
    { 18, 10, 13, 1, 1 },  // water-in-gap
    { 36, 10, 13, 1, 1 },  // water-in-gap
    { 6, 7, 14, 1, 1 },  // tree
    { 58, 7, 14, 1, 1 },  // tree
    { 92, 7, 12, 1, 1 },  // goal-sign
};
int i = 0;
int n = sizeof(m) / sizeof(m[0]);
while (i < n && i < MAP_NUMBER)
{
    switch (m[i].id)
    {
    case 1: case 2: case 3: case 4: case 5:
        m[i].u = (V_MAX / T2) / G; break;
    case 6:
        m[i].u = (V_MAX / T1) / G; break;
    default:
        m[i].u = (V_MAX / T3) / G; break;
    }
    map[i] = m[i];
    i++;
}
#endif

#if 0  // ----- Scene::createCoin  (world == 4) -----
POINT p[] = {
    { 12, 8 }, { 13, 8 }, { 16, 6 }, { 17, 6 },
    { 19, 4 }, { 20, 4 }, { 33, 5 }, { 34, 5 },
    { 35, 5 }, { 49, 8 }, { 52, 5 }, { 63, 8 },
};
for (int i = 0; i < (int)(sizeof(p) / sizeof(p[0])) && i < COINS_NUMBER; i++)
{
    coins[i].x = p[i].x;
    coins[i].y = p[i].y;
}
#endif

#if 0  // ----- Scene::createFood  (world == 4) -----
POINT f[] = {
    { 26 * WIDTH, 8 * HEIGHT },
};
for (int i = 0; i < (int)(sizeof(f) / sizeof(f[0])) && i < FOOD_NUMBER; i++)
{
    food[i].x = f[i].x;
    food[i].y = f[i].y;
}
#endif

#if 0  // ----- Role::createEnemy  (world == 4) -----
Enemy emy[] = {
    { 8, 8, 1 }, { 24, 8, -1 }, { 30, 8, 1 },
    { 42, 8, -1 }, { 60, 8, 1 }, { 74, 8, -1 },
};
for (int i = 0; i < (int)(sizeof(emy) / sizeof(emy[0])) && i < ENEMY_TOTE; i++)
{
    myEnemy[i].x = emy[i].x * WIDTH;
    myEnemy[i].y = emy[i].y * HEIGHT;
    myEnemy[i].turn = emy[i].turn;
}
#endif

#if 0  // ----- Scene::isEnding -----
case 4:
    if (distance > 88 * WIDTH)
        return true;
    return false;
#endif

int maoliao_snippet_world4_placeholder()
{
    // Keeps a translation unit valid if someone adds this file to a dummy target.
    return 88;
}
